#!/bin/bash

echo "Installing NVIM configuration"

NVIM_DIR=~/.config/nvim

if [ ! -d "$NVIM_DIR" ]
then
        mkdir -p "$NVIM_DIR"
else
        mv $NVIM_DIR ~/.config/nvim_oldfiles
fi

# If offline installation option set
if [[ $1 = "-o" ]]
then
        PLUGINS_DATA_TAR=./plugins_data.tar.gz
        if [ -f $PLUGINS_DATA_TAR ]
        then
                echo "Extracting plugins data"
                EXTRACTION_DIR="$(pwd)/plugins/lazy"
                mkdir -p $EXTRACTION_DIR
                tar -xf $PLUGINS_DATA_TAR -C $EXTRACTION_DIR
                ln -s "$(pwd)/plugins" "$NVIM_DIR"
        else
                echo "Error: missing plugins_data tarball"
                exit 1
        fi

        PLUGINS_TAR=./custom_plugins.tar.gz
        if [ -f $PLUGINS_TAR ]
        then
                echo "Extracting custom plugins"
                PLUGINS_DIR="$NVIM_DIR/lua/custom/plugins"
                PLUGIN_EXTRACTION_TARGET_DIR="$(pwd)/lua/custom/plugins_off"
                mkdir -p $PLUGIN_EXTRACTION_TARGET_DIR
                tar -xf $PLUGINS_TAR -C $PLUGIN_EXTRACTION_TARGET_DIR
                mkdir -p $PLUGINS_DIR
                ln -s $PLUGIN_EXTRACTION_TARGET_DIR $PLUGINS_DIR
        else
                echo "Error: missing custom_plugins tarball"
                exit 2
        fi

        ln -s "$(pwd)/init_off.lua" $NVIM_DIR/init.lua
else
        ln -s "$(pwd)/lua" $NVIM_DIR
        ln -s "$(pwd)/init.lua" $NVIM_DIR/init.lua
fi

echo "All done!"
exit 0
